accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('articles/create/', views.create, name='create'),
    path('articles/<int:article_pk>/', views.detail, name='detail'),
    path('articles/<str:category_name>/', views.category_name, name='category_name'),
    path('articles/<int:article_pk>/delete/', views.delete, name='delete'),
    path('articles/<int:article_pk>/update/', views.update, name='update'),
    path('articles/<int:article_pk>/comments/', views.comment_create, name='comment_create'),
    path('articles/<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('articles/<int:article_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('articles/<int:article_pk>/reviews/create/', views.review_create, name='review_create'),
    path('reviews/<int:review_pk>/', views.review_detail, name='review_detail'),
    path('reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('reviews/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('reviews/<int:review_pk>/comments/', views.review_comment_create, name='review_comment_create'),
    path('reviews/<int:review_pk>/comments/<int:comment_pk>/delete/', views.review_comment_delete, name='review_comment_delete'),
    path('reviews/<int:review_pk>/comments/<int:comment_pk>/update/', views.review_comment_update, name='review_comment_update'),
    path('articles/<int:pk>/emotes/<int:emotion>/<str:page>/', views.emotes, name='emotes'),
    path('search/', views.search, name='search'),
    path('search/<str:category>/', views.search_detail, name='search_detail'),
    path('plan/', views.plan, name='plan'),
    path('plan/<int:plan_pk>/delete/', views.plan_delete, name='plan_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/forms.py
from django import forms
from django.forms import ClearableFileInput
from .models import Article, Comment, Review, ReviewComment, Emote, Plan, ArticlePlan


class ArticleForm(forms.ModelForm):
    CATEGORY_CHOICES = [
        ('숙소','숙소'),
        ('자연명소','자연명소'),
        ('테마파크','테마파크'),
        ('체험관광','체험관광'),
        ('레저 & 액티비티','레저 & 액티비티'),
        ('맛집','맛집'),
        ('쇼핑','쇼핑'),
    ]
    category = forms.ChoiceField(
        label = '카테고리',
        widget = forms.Select(
            attrs = {
                'class': 'my-category form-control',
                'style': 'border:none;'
            }
        ),
        choices = CATEGORY_CHOICES,
    )
    class Meta:
        model = Article
        exclude = ('user', 'emote_users')
        labels = {
            'title': '제목',
            'content': '내용',
            'image': '이미지',
        }
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder' : '제목을 입력해 주세요',
                    'style': 'border:none;',
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder' : '내용을 입력해 주세요',
                    'rows':'10',
                    'style': 'border:none;'
                }
            ),
            'image': ClearableFileInput(
                attrs={
                    'class': 'form-control',
                    'style': 'width: 400px;'
                }
            ),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        labels = {
            'content': '',
        }
        widgets = {
            'content': forms.Textarea(attrs={'class':'form-control', 'rows':'2'})
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.errors:
            for f_name in self.fields:
                if f_name in self.errors:
                    self.fields[f_name].widget.attrs.update({'aria-describedby': f"{f_name}_invalid"})
                    self.fields[f_name].widget.attrs.update({'aria-invalid': 'true'})
                    self.errors.pop(f_name)
                else:
                    self.fields[f_name].widget.attrs.update({'class': 'form-control'})
                    self.fields[f_name].widget.attrs.update({'aria-describedby': f"{f_name}_help"})
                    self.fields[f_name].widget.attrs.update({'aria-invalid': 'false'})


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ('user', 'emote_users', 'article',)
        labels = {
                'title': '제목',
                'content': '내용',
                'image': '이미지',    
                'score': '별점',
            }
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder' : '제목을 입력해 주세요',
                    'style': 'border:none;',
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder' : '내용을 입력해 주세요',
                    'style': 'border:none;',
                    'rows':'5',
                }
            ),
            'image': ClearableFileInput(
                attrs={
                    'class': 'form-control',
                    'style': 'width: 400px;'
                }
            ),
            'score': forms.NumberInput(
                attrs={
                    'class':'form-control',
                    'style': 'border:none;'
                }
            ),
        }


class ReviewCommentForm(forms.ModelForm):
    class Meta:
        model = ReviewComment
        fields = ('content',)
        labels = {
            'content': '',
        }
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class':'form-control', 
                    'rows':'2',
                }
            )
        }
        
        
class EmoteForm(forms.ModelForm):
    class Meta:
        model = Emote
        fields = ('emotion',)
        

class PlanForm(forms.ModelForm):
    class Meta:
        model = Plan
        fields = ('startday_at', 'endday_at')
    startday_at = forms.DateField(label='여행 시작일', label_suffix='', widget=forms.DateInput(
        attrs={'class': 'form-control', 'type': 'date',  'style': 'width: 300px;'}))
    endday_at = forms.DateField(label='여행 종료일', label_suffix='', widget=forms.DateInput(
        attrs={'class': 'form-control', 'type': 'date',  'style': 'width: 300px;'}))
        

class ArticlePlanForm(forms.ModelForm):
    class Meta:
        model = ArticlePlan
        fields = ('day',)
    day = forms.IntegerField(label='총 일수', label_suffix='', widget=forms.NumberInput(
        attrs={'class': 'form-control', 'style': 'width: 400px;'}))

articles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.db.models import Q
from django.core.paginator import Paginator
from .models import Article, Comment, Review, ReviewComment, Emote, Plan, ArticlePlan
from .forms import ArticleForm, CommentForm, ReviewForm, ReviewCommentForm, PlanForm, ArticlePlanForm
import json
import random
from geopy.geocoders import Nominatim

# Create your views here.

def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


EMOTIONS = [
    {'label': '좋아요', 'value': 1},
    {'label': '재밌어요', 'value': 2},
    {'label': '그냥그래요', 'value': 3},
]


def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    User = get_user_model()
    users = User.objects.all()
    geolocoder = Nominatim(user_agent = 'South Korea', timeout=None)
    address = geolocoder.reverse((article.lat, article.lng))
    reviews = Review.objects.filter(article=article_pk)
    review_count = reviews.count()
    comments = article.comment_set.all()
    comment_count = comments.count()
    comment_form = CommentForm()
    form = CommentForm(request.POST, instance=article)
    emotions = []
    for emotion in EMOTIONS:
        label = emotion['label']
        value = emotion['value']
        count = Emote.objects.filter(article=article, emotion=value).count()
        if request.user.is_authenticated:
            exist = Emote.objects.filter(article=article, emotion=value, user=request.user)
        else:
            exist = False
        emotions.append(
            {
                'label': label,
                'value': value,
                'count': count,
                'exist': exist,
            }
        )
    context = {
        'article': article,
        'users': users,
        'comments': comments,
        'comment_form': comment_form,
        'form': form,
        'reviews': reviews,
        'review_count': review_count,
        'comment_count': comment_count,
        'emotions': emotions,
        'address' : address,
    }
    return render(request, 'articles/detail.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)


@login_required
def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if article.user == request.user:
        article.delete()
    return redirect('articles:index')


@login_required
def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)


@login_required
def comment_create(request, article_pk):
    if request.method == "POST":
        article = Article.objects.get(pk=article_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
        return redirect('articles:detail', article.pk)


@login_required
def comment_delete(request, article_pk, comment_pk):
    if request.method == "POST":
        comment = Comment.objects.get(pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('articles:detail', article_pk)


@login_required
def comment_update(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        if request.method == 'POST':
            r = list(request.POST.keys())
            js = json.loads(r[0])
            comment.content = js['content']
            comment.save()
    context = {
        'content': comment.content,
    }
    return JsonResponse(context)


def review_detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    article = Article.objects.get(pk=review.article_id)
    geolocoder = Nominatim(user_agent = 'South Korea', timeout=None)
    address = geolocoder.reverse((article.lat, article.lng))
    User = get_user_model()
    users = User.objects.all()
    comments = review.reviewcomment_set.all()
    comment_form = ReviewCommentForm()
    comment_count = comments.count()
    emotions = []
    for emotion in EMOTIONS:
        label = emotion['label']
        value = emotion['value']
        count = Emote.objects.filter(review=review, emotion=value).count()
        if request.user.is_authenticated:
            exist = Emote.objects.filter(review=review, emotion=value, user=request.user)
        else:
            exist = False
        emotions.append(
            {
                'label': label,
                'value': value,
                'count': count,
                'exist': exist,
            }
        )
    context = {
        'users': users,
        'review': review,
        'article': article,
        'comments': comments,
        'comment_form': comment_form,
        'emotions': emotions,
        'comment_count': comment_count,
        'address': address,
    }
    return render(request, 'reviews/review_detail.html', context)


@login_required
def review_create(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.article = article
            review.user = request.user
            review.save()
            return redirect('articles:review_detail', review.pk)
    else:
        form = ReviewForm()
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'reviews/review_create.html', context)
    

@login_required
def review_delete(request, review_pk):    
    review = Review.objects.get(pk=review_pk)
    article_pk = review.article.pk
    if review.user == request.user:
        review.delete()
    return redirect('articles:detail', article_pk)


@login_required
def review_update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    article_pk = review.article.pk
    if request.user == review.user:
        if request.method == 'POST':
            form = ReviewForm(request.POST, request.FILES, instance=review)
            if form.is_valid():
                form.save()
                return redirect('articles:review_detail', review_pk)
        else:
            form = ReviewForm(instance=review)
    else:
        return redirect('articles:review_detail', article_pk)
    context = {
        'review': review,
        'form': form,
    }
    return render(request, 'reviews/review_update.html', context)


@login_required
def review_comment_create(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    form = ReviewCommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
        return redirect('articles:review_detail', review.pk)
    

@login_required
def review_comment_delete(request, review_pk, comment_pk):
    comment = ReviewComment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('articles:review_detail', review_pk)


@login_required
def review_comment_update(request, review_pk, comment_pk):
    comment = ReviewComment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        if request.method == 'POST':
            r = list(request.POST.keys())
            js = json.loads(r[0])
            comment.content = js['content']
            comment.save()
    context = {
        'content': comment.content,
    }
    return JsonResponse(context)


def category_name(request, category_name):
    articles = Article.objects.filter(category=category_name).order_by('-pk')
    length = articles.count()
    page = request.GET.get('page', '1')
    per_page = 5
    paginator = Paginator(articles, per_page)
    page_obj = paginator.get_page(page)
    num_page = paginator.num_pages
    context = {
        'articles': page_obj,
        'category_name': category_name,
        'num_page': num_page,
        'length': length,
    }
    return render(request, 'articles/category_name.html', context)


@login_required
def emotes(request, pk, emotion, page):
    if 'Article' in page:
        article = Article.objects.get(pk=pk)
        filter_query = Emote.objects.filter(article=article, user=request.user, emotion=emotion)
        if filter_query.exists():
            filter_query.delete()
        else:
            Emote.objects.create(article=article, user=request.user, emotion=emotion)
        context = {
            'emotion_count': Emote.objects.filter(article=article, emotion=emotion).count()
        }
        return JsonResponse(context)
    elif 'Review' in page:
        review = Review.objects.get(pk=pk)
        filter_query = Emote.objects.filter(review=review, user=request.user, emotion=emotion)

articles/templates/search/search.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static '/CSS/search.css' %}">
{% endblock head %}

{% block content %}
  <h3>여행지 검색 결과
    <span class="count">
      {% if article_count > 0 %}
        ({{article_count}}개)
      {% endif %}
    </span>
  </h3>
  <table class="table table_hover align-middle">
    <thead>
      <tr>
        <th scope="col" width="20%">여행지</th>
        <th scope="col" width="10%">이미지</th>
        <th scope="col" width="15%">작성자</th>
        <th scope="col" >내용</th>
        <th scope="col" width="10%">작성일</th>
      </tr>
    </thead>
    <tbody>
      {% for result in results_article %}
      <tr>
        <td><a href="{% url 'articles:detail' result.pk %}" class="link">{{ result.title|truncatechars:10 }}</a></td>
        <td><img src="{{result.image.url}}" alt="이미지" class="table_image"></td>
        <td><a href="{% url 'accounts:profile' result.user %}" class="link">{{ result.user }}</a></td>
        <td>{{result.content|truncatechars:25}}</td>
        <td>{{result.created_at|date:"Y-m-d"}}</td>
      </tr>
      {% empty %}
        <td colspan="6" class="noresult">검색 결과가 없습니다. </td>
      {% endfor %}
    </tbody>
  </table>
  {% if article_count > 5 %}
    <form action="{% url 'articles:search_detail' 'article' %}" method="GET" class="search_more">
      <button type="submit" name="word" value="{{search_word}}" class="btn btn-sm link">여행지 검색 결과 더 보기</button>
    </form> 
  {% endif %}

  <hr>
  
  <h3 class="pt-4">리뷰 검색 결과
    <span class="count">
      {% if review_count > 0 %}
        ({{review_count}}개)
      {% endif %}
    </span>
  </h3>
  <table class="table table_hover align-middle">
    <thead>
      <tr>
        <th scope="col" width="20%">리뷰</th>
        <th scope="col" width="10%">이미지</th>
        <th scope="col" width="15%">작성자</th>
        <th scope="col" >내용</th>
        <th scope="col" width="10%">작성일</th>
      </tr>
    </thead>
    <tbody>
      {% for result in results_review %}
      <tr>
        <td><a href="{% url 'articles:review_detail' result.pk %}" class="link">{{ result.title|truncatechars:10 }}</a></td>
        <td><img src="{{result.image.url}}" alt="이미지" class="table_image"></td>
        <td><a href="{% url 'accounts:profile' result.user %}" class="link">{{ result.user }}</a></td>
        <td>{{result.content|truncatechars:25}}</td>
        <td>{{result.created_at|date:"Y-m-d"}}</td>
      </tr>
      {% empty %}
        <td colspan="6" class="noresult">검색 결과가 없습니다. </td>
      {% endfor %}
    </tbody>
  </table>
  {% if review_count > 5 %}
    <form action="{% url 'articles:search_detail' 'review' %}" method="GET" class="search_more">
      <button type="submit" name="word" value="{{search_word}}" class="btn btn-sm link">리뷰 검색 결과 더 보기</button>
    </form> 
  {% endif %}
{% endblock content %}

articles/templates/search/search_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static '/CSS/search.css' %}">
{% endblock head %}

{% block content %}
  <h3>
    {% if category == "Article" %}
      여행지
    {% else %}
      리뷰
    {% endif %}
    상세 검색 결과
  </h3>
  <table class="table table_hover align-middle">
    <thead>
      <tr>
        {% comment %} <th scope="col" width="5%"></th> {% endcomment %}
        <th scope="col" width="20%">
        {% if category == "Article" %}
          여행지
        {% else %}
          리뷰
        {% endif %}</th>
        <th scope="col" width="10%">이미지</th>
        <th scope="col" width="15%">작성자</th>
        <th scope="col" >내용</th>
        <th scope="col" width="10%">작성일</th>
      </tr>
    </thead>
    <tbody>
      {% for result in results %}
      <tr>
        {% comment %} <th scope="row">{{results.start_index|add:forloop.counter0}}</th> {% endcomment %}
        <td><a href="{% url 'articles:review_detail' result.pk %}" class="link">{{ result.title|truncatechars:10 }}</a></td>
        <td><img src="{{result.image.url}}" alt="이미지" class="table_image"></td>
        <td><a href="{% url 'accounts:profile' result.user %}" class="link">{{ result.user }}</a></td>
        <td>{{result.content|truncatechars:25}}</td>
        <td>{{result.created_at|date:"Y-m-d"}}</td>
      </tr>
      {% empty %}
        <td colspan="6" class="noresult">검색 결과가 없습니다. </td>
      {% endfor %}
    </tbody>
  </table>

  <ul class="pagination justify-content-center">
    {% if results.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?word={{search_word}}&page=1">처음</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?word={{search_word}}&page={{ results.previous_page_number }}">이전</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
      </li>
    {% endif %}
    {% for page_number in results.paginator.page_range %}
    {% if page_number >= results.number|add:-5 and page_number <= results.number|add:5 %}
        {% if page_number == results.number %}
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="?word={{search_word}}&page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?word={{search_word}}&page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endif %}
    {% endfor %}
    {% if results.has_next %}
      <li class="page-item">
        <a href="?word={{search_word}}&page={{ results.next_page_number }}" class="page-link" name="word">다음</a>
      </li>
      <li class="page-item">
        <a href="?word={{search_word}}&page={{ num_page }}" class="page-link">마지막으로</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a href="#" class="page-link" tabindex='-1' aria-disabled='true'>다음</a>
      </li>
    {% endif %}
  </ul>
{% endblock content %}  