accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('articles/create/', views.create, name='create'),
    path('articles/<int:article_pk>/', views.detail, name='detail'),
    path('articles/<str:category_name>/', views.category_name, name='category_name'),
    path('articles/<int:article_pk>/delete/', views.delete, name='delete'),
    path('articles/<int:article_pk>/update/', views.update, name='update'),
    path('articles/<int:article_pk>/comments/', views.comment_create, name='comment_create'),
    path('articles/<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('articles/<int:article_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('articles/<int:article_pk>/reviews/create/', views.review_create, name='review_create'),
    path('reviews/<int:review_pk>/', views.review_detail, name='review_detail'),
    path('reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('reviews/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('reviews/<int:review_pk>/comments/', views.review_comment_create, name='review_comment_create'),
    path('reviews/<int:review_pk>/comments/<int:comment_pk>/delete/', views.review_comment_delete, name='review_comment_delete'),
    path('reviews/<int:review_pk>/comments/<int:comment_pk>/update/', views.review_comment_update, name='review_comment_update'),
    path('articles/<int:pk>/emotes/<int:emotion>/<str:page>/', views.emotes, name='emotes'),
    path('search/', views.search, name='search'),
    path('search/<str:category>/', views.search_detail, name='search_detail'),
    path('plan/', views.plan, name='plan'),
    path('plan/<int:plan_pk>/delete/', views.plan_delete, name='plan_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/forms.py
from django import forms
from django.forms import ClearableFileInput
from .models import Article, Comment, Review, ReviewComment, Emote, Plan, ArticlePlan


class ArticleForm(forms.ModelForm):
    CATEGORY_CHOICES = [
        ('숙소','숙소'),
        ('자연명소','자연명소'),
        ('테마파크','테마파크'),
        ('체험관광','체험관광'),
        ('레저 & 액티비티','레저 & 액티비티'),
        ('맛집','맛집'),
        ('쇼핑','쇼핑'),
    ]
    category = forms.ChoiceField(
        label = '카테고리',
        widget = forms.Select(
            attrs = {
                'class': 'my-category form-control',
                'style': 'border:none;'
            }
        ),
        choices = CATEGORY_CHOICES,
    )
    class Meta:
        model = Article
        exclude = ('user', 'emote_users')
        labels = {
            'title': '제목',
            'content': '내용',
            'image': '이미지',
        }
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder' : '제목을 입력해 주세요',
                    'style': 'border:none;',
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder' : '내용을 입력해 주세요',
                    'rows':'10',
                    'style': 'border:none;'
                }
            ),
            'image': ClearableFileInput(
                attrs={
                    'class': 'form-control',
                    'style': 'width: 400px;'
                }
            ),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        labels = {
            'content': '',
        }
        widgets = {
            'content': forms.Textarea(attrs={'class':'form-control', 'rows':'2'})
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.errors:
            for f_name in self.fields:
                if f_name in self.errors:
                    self.fields[f_name].widget.attrs.update({'aria-describedby': f"{f_name}_invalid"})
                    self.fields[f_name].widget.attrs.update({'aria-invalid': 'true'})
                    self.errors.pop(f_name)
                else:
                    self.fields[f_name].widget.attrs.update({'class': 'form-control'})
                    self.fields[f_name].widget.attrs.update({'aria-describedby': f"{f_name}_help"})
                    self.fields[f_name].widget.attrs.update({'aria-invalid': 'false'})


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ('user', 'emote_users', 'article',)
        labels = {
                'title': '제목',
                'content': '내용',
                'image': '이미지',    
                'score': '별점',
            }
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder' : '제목을 입력해 주세요',
                    'style': 'border:none;',
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder' : '내용을 입력해 주세요',
                    'style': 'border:none;',
                    'rows':'5',
                }
            ),
            'image': ClearableFileInput(
                attrs={
                    'class': 'form-control',
                    'style': 'width: 400px;'
                }
            ),
            'score': forms.NumberInput(
                attrs={
                    'class':'form-control',
                    'style': 'border:none;'
                }
            ),
        }


class ReviewCommentForm(forms.ModelForm):
    class Meta:
        model = ReviewComment
        fields = ('content',)
        labels = {
            'content': '',
        }
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class':'form-control', 
                    'rows':'2',
                }
            )
        }
        
        
class EmoteForm(forms.ModelForm):
    class Meta:
        model = Emote
        fields = ('emotion',)
        

class PlanForm(forms.ModelForm):
    class Meta:
        model = Plan
        fields = ('startday_at', 'endday_at')
    startday_at = forms.DateField(label='여행 시작일', label_suffix='', widget=forms.DateInput(
        attrs={'class': 'form-control', 'type': 'date',  'style': 'width: 300px;'}))
    endday_at = forms.DateField(label='여행 종료일', label_suffix='', widget=forms.DateInput(
        attrs={'class': 'form-control', 'type': 'date',  'style': 'width: 300px;'}))
        

class ArticlePlanForm(forms.ModelForm):
    class Meta:
        model = ArticlePlan
        fields = ('day',)
    day = forms.IntegerField(label='총 일수', label_suffix='', widget=forms.NumberInput(
        attrs={'class': 'form-control', 'style': 'width: 400px;'}))

articles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.db.models import Q
from django.core.paginator import Paginator
from .models import Article, Comment, Review, ReviewComment, Emote, Plan, ArticlePlan
from .forms import ArticleForm, CommentForm, ReviewForm, ReviewCommentForm, PlanForm, ArticlePlanForm
import json
import random
from geopy.geocoders import Nominatim

# Create your views here.

def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


EMOTIONS = [
    {'label': '좋아요', 'value': 1},
    {'label': '재밌어요', 'value': 2},
    {'label': '그냥그래요', 'value': 3},
]


def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    User = get_user_model()
    users = User.objects.all()
    geolocoder = Nominatim(user_agent = 'South Korea', timeout=None)
    address = geolocoder.reverse((article.lat, article.lng))
    reviews = Review.objects.filter(article=article_pk)
    review_count = reviews.count()
    comments = article.comment_set.all()
    comment_count = comments.count()
    comment_form = CommentForm()
    form = CommentForm(request.POST, instance=article)
    emotions = []
    for emotion in EMOTIONS:
        label = emotion['label']
        value = emotion['value']
        count = Emote.objects.filter(article=article, emotion=value).count()
        if request.user.is_authenticated:
            exist = Emote.objects.filter(article=article, emotion=value, user=request.user)
        else:
            exist = False
        emotions.append(
            {
                'label': label,
                'value': value,
                'count': count,
                'exist': exist,
            }
        )
    context = {
        'article': article,
        'users': users,
        'comments': comments,
        'comment_form': comment_form,
        'form': form,
        'reviews': reviews,
        'review_count': review_count,
        'comment_count': comment_count,
        'emotions': emotions,
        'address' : address,
    }
    return render(request, 'articles/detail.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)


@login_required
def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if article.user == request.user:
        article.delete()
    return redirect('articles:index')


@login_required
def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)


@login_required
def comment_create(request, article_pk):
    if request.method == "POST":
        article = Article.objects.get(pk=article_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
        return redirect('articles:detail', article.pk)


@login_required
def comment_delete(request, article_pk, comment_pk):
    if request.method == "POST":
        comment = Comment.objects.get(pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('articles:detail', article_pk)


@login_required
def comment_update(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        if request.method == 'POST':
            r = list(request.POST.keys())
            js = json.loads(r[0])
            comment.content = js['content']
            comment.save()
    context = {
        'content': comment.content,
    }
    return JsonResponse(context)


def review_detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    article = Article.objects.get(pk=review.article_id)
    geolocoder = Nominatim(user_agent = 'South Korea', timeout=None)
    address = geolocoder.reverse((article.lat, article.lng))
    User = get_user_model()
    users = User.objects.all()
    comments = review.reviewcomment_set.all()
    comment_form = ReviewCommentForm()
    comment_count = comments.count()
    emotions = []
    for emotion in EMOTIONS:
        label = emotion['label']
        value = emotion['value']
        count = Emote.objects.filter(review=review, emotion=value).count()
        if request.user.is_authenticated:
            exist = Emote.objects.filter(review=review, emotion=value, user=request.user)
        else:
            exist = False
        emotions.append(
            {
                'label': label,
                'value': value,
                'count': count,
                'exist': exist,
            }
        )
    context = {
        'users': users,
        'review': review,
        'article': article,
        'comments': comments,
        'comment_form': comment_form,
        'emotions': emotions,
        'comment_count': comment_count,
        'address': address,
    }
    return render(request, 'reviews/review_detail.html', context)


@login_required
def review_create(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.article = article
            review.user = request.user
            review.save()
            return redirect('articles:review_detail', review.pk)
    else:
        form = ReviewForm()
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'reviews/review_create.html', context)
    

@login_required
def review_delete(request, review_pk):    
    review = Review.objects.get(pk=review_pk)
    article_pk = review.article.pk
    if review.user == request.user:
        review.delete()
    return redirect('articles:detail', article_pk)


@login_required
def review_update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    article_pk = review.article.pk
    if request.user == review.user:
        if request.method == 'POST':
            form = ReviewForm(request.POST, request.FILES, instance=review)
            if form.is_valid():
                form.save()
                return redirect('articles:review_detail', review_pk)
        else:
            form = ReviewForm(instance=review)
    else:
        return redirect('articles:review_detail', article_pk)
    context = {
        'review': review,
        'form': form,
    }
    return render(request, 'reviews/review_update.html', context)


@login_required
def review_comment_create(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    form = ReviewCommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
        return redirect('articles:review_detail', review.pk)
    

@login_required
def review_comment_delete(request, review_pk, comment_pk):
    comment = ReviewComment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('articles:review_detail', review_pk)


@login_required
def review_comment_update(request, review_pk, comment_pk):
    comment = ReviewComment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        if request.method == 'POST':
            r = list(request.POST.keys())
            js = json.loads(r[0])
            comment.content = js['content']
            comment.save()
    context = {
        'content': comment.content,
    }
    return JsonResponse(context)


def category_name(request, category_name):
    articles = Article.objects.filter(category=category_name).order_by('-pk')
    length = articles.count()
    page = request.GET.get('page', '1')
    per_page = 5
    paginator = Paginator(articles, per_page)
    page_obj = paginator.get_page(page)
    num_page = paginator.num_pages
    context = {
        'articles': page_obj,
        'category_name': category_name,
        'num_page': num_page,
        'length': length,
    }
    return render(request, 'articles/category_name.html', context)


@login_required
def emotes(request, pk, emotion, page):
    if 'Article' in page:
        article = Article.objects.get(pk=pk)
        filter_query = Emote.objects.filter(article=article, user=request.user, emotion=emotion)
        if filter_query.exists():
            filter_query.delete()
        else:
            Emote.objects.create(article=article, user=request.user, emotion=emotion)
        context = {
            'emotion_count': Emote.objects.filter(article=article, emotion=emotion).count()
        }
        return JsonResponse(context)
    elif 'Review' in page:
        review = Review.objects.get(pk=pk)
        filter_query = Emote.objects.filter(review=review, user=request.user, emotion=emotion)

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static '/CSS/review_detail.css' %}">
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% endblock head %}

{% block content %}
<h6 class="small">제주도 > {{article.category}}</h6>

<div class="row">
  <div class="col-10">
    <h4><strong>{{article.title}}</strong></h4>
  </div> 
  <div class="col-2 d-flex justify-content-end align-items-end"> 
    <a href="{% url 'accounts:profile' username=article.user %}" style="text-decoration:none;"> <img style="color: black; width:32px; height:32px; border-radius:50%;" src={% if article.user.profile_img %} "{{ article.user.profile_img.url }}" {% else %} "{% static '/img/user_image.png' %}" {% endif %} alt="프로필 사진" id="profile-image"/>
      <span class="small" style='color:black;'><strong>{{article.user}}</strong></span>
    </a> 
    
  </div>
</div>

<hr>

<p class="small d-flex justify-content-end">생성 날짜 : {{article.created_at|date:"Y-m-d"}}</p>

<div class="row d-flex justify-content-center mt-2 p-2 mb-5">
  <div class="col-7 text-center shadow rounded border-light m-2 p-4" style="width:600px;"> 
    <div class="row-6" style="width:100%">
      {% if article.image %}
      <img src="{{article.image.url}}" class="object-fit-cover" alt="">
      {% endif %}
    </div>
    <div class="row-6 d-flex justify-content-center">
      <div id="map" style="width:500px; height:300px;" class="object-fit-cover"></div>
    </div>
      
  </div>
  <div class="col-5 mx-3 shadow rounded border-light my-2 p-4" style="width: 600px"> 
    <p><strong>기본 정보</strong></p>
    <hr>
    <div style="" >
      <table class="table" style="" >
        <tbody>
          <tr>
            <th scope="row" style="width:150px;">주소</th>
            <td>{{address}}</td>
          </tr>
          <tr>
            <th scope="row" style="width:150px;">내용</th>
            <td style="width: 600px; height:300px;">{{article.content|linebreaksbr}}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="row">
      <div class="col-6">
        <div class="d-flex text-center">
          {% for emotion in emotions %}
          <div class="m-3" id="emotion-{{emotion.value}}">
            {{ emotion.queryset }}
              <form>
                {% if request.user.is_authenticated %}
                  {% csrf_token %}
                  {% if emotion.exist %}
                    <input type="image" src="{% static 'emotions/' %}{{ emotion.value }}.png" value="{{ emotion.label }} 취소" style="width: 25px; height: 25px;" class="emotion" data-emotion-id="{{emotion.value}}">
                  {% else %}
                    <input type="image" src="{% static 'emotions/' %}{{ emotion.value }}.png" value="{{ emotion.label }}" style="width: 25px; height: 25px;" class="emotion" data-emotion-id="{{emotion.value}}">
                  {% endif %}
                {% else %}
                  <input type="image" src="{% static 'emotions/' %}{{ emotion.value }}.png" value="{{ emotion.label }}" style="width: 25px; height: 25px;" class="emotion" disabled>
                {% endif %}
              </form>
            <span class="emotion-count small">{{ emotion.count }}</span>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="col-6">
        {% if request.user == article.user %}
          <div class="d-inline-block d-flex justify-content-end align-items-end">
            <a href="{% url 'articles:update' article.pk %}" class="p-2"><button type="button" class="btn btn-outline-primary">수정하기</button></a>
            <form action="{% url 'articles:delete' article.pk %}" METHOD="POST" class="p-2">
              {% csrf_token %}
              <button type="submit" value="DELETE" class="btn btn-outline-danger">삭제하기</button>
            </form>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% comment %} 리뷰 목록 {% endcomment %}
<div class="row mt-4" >
  <hr>
  <h5 class="col-6 fw-bold">리뷰 <span style="color:green;">{{review_count}}</span></h5>
  <a href="{% url 'articles:review_create' article.pk %}" class="col-6 p-2  d-flex justify-content-end align-items-start " style="text-decoration:none;"><button type="button" class="btn btn-sm btn-outline-success">리뷰 남기기</button></a>
</div>

{% for review in reviews %}
  <div class="row shadow rounded border-light p-2 mb-3" style="cursor: pointer;" onclick="location.href='{% url 'articles:review_detail' review.pk %}';" >
    <div class="col-1">
      <div class="row-8 d-flex justify-content-center align-items-center mt-2">
        <img class="" style="width:50px; height:50px; border-radius:50%;" src={% if review.user.profile_img %} "{{ review.user.profile_img.url }}" {% else %} "{% static '/img/user_image.png' %}" {% endif %} alt="프로필 사진" id="profile-image"/>
      </div>
      <div class="row-4 text-center small">
          <strong>{{review.user}}</strong>  
          <br>  
          {{review.created_at|date:"Y-m-d"}}    
        <p id="stars-{{review.pk}}" class="mt-3 mb-3 text-center" style="font-size: 10px;"></p>
      </div>
    </div>
    <div class="col-11">
      <div class="row-4">
        <p class="box"><strong>{{ review.title }}</strong></p>
      </div>
      <hr class="row-1">
      <div class="row-7">
        {% if review.image %}
          <img src="{{review.image.url}}" alt="travel_review_image" style="width:200px;">
        {% endif %}          
      <p class="my-2 box text-truncate" style="height:100px;">{{ review.content|linebreaksbr }}</p>        
      </div>
    </div>
  </div>
{% endfor %}

<hr>

{% comment %} 댓글 목록 {% endcomment %}
<div class="mt-4" style="">
  <h5 class="mb-4 fw-bold">댓글<span style="color:green;">{{comment_count}}</span></h5>

  <hr>

  {% for comment in comments %}
    <div class="d-flex">
      <img style="width:32px; height:32px; border-radius:50%;" src={% if comment.user.profile_img %} "{{ comment.user.profile_img.url }}" {% else %} "{% static '/img/user_image.png' %}" {% endif %} alt="프로필 사진" id="profile-image"/>
      <p class="ps-2">
        <strong class="comment-user">{{comment.user}}</strong>
      </p>
    </div>
    <p id="comment-content-{{comment.pk}}">{{comment.content}}</p>
    
    <div>
      {% if user.id == comment.user_id %}
      <div class="d-flex">
        <input type="button" value="댓글 수정" class="comment-edit-btn btn btn-sm btn-outline-primary me-4" data-article-id="{{ article.pk }}" data-comment-id="{{ comment.pk }}">
        <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="댓글 삭제" class="btn btn-sm btn-outline-danger">
        </form>
      </div>
      {% endif %}
      <hr>

      <form class="comment-edit-form my-3" id="comment-edit-form-{{ comment.pk }}" data-article-id="{{ article.pk }}" data-comment-id="{{ comment.pk }}" hidden>
        {% csrf_token %}
        {{comment_form.as_p}}
        <input type="submit" value="수정" class="update btn btn-sm btn-outline-primary">
        <input type="button" value="취소" class="cancel btn btn-sm btn-outline-secondary" data-comment-id="{{ comment.pk }}">
      </form>
    </div>
  {% endfor %}

  <hr>
  <form action="{% url 'articles:comment_create' article.pk %}" method="post">
    {% csrf_token %}
    <div class="main" style="border-bottom: 1px solid #198754; width:100%">
      댓글 작성 : {{ comment_form.content }}
    </div>
    <input type="submit" class="btn btn-sm btn-outline-success mt-3" value="댓글 작성">    
  </form>
</div>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=44fdfd5aea6498bf2814ede3eae827b6&libraries=services,clusterer,drawing"></script>
<script>
  // 카카오맵
  var container = document.getElementById('map')
  var options = {
    center: new kakao.maps.LatLng({{article.lat}}, {{article.lng}}),
    level: 5
  }
  var map = new kakao.maps.Map(container, options)
  var markerPosition = options.center
  var marker = new kakao.maps.Marker({
    position: markerPosition
  })
  marker.setMap(map)

  // 댓글 수정
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
  const commentUpdates = document.querySelectorAll('.comment-edit-btn')

  commentUpdates.forEach((comment) => {
    comment.addEventListener('click', (event) => {
      const commentId = event.target.dataset.commentId
      const commentUpdateDiv = document.querySelector(`#comment-edit-form-${commentId}`)
      const contentTextArea = document.querySelector(`#comment-edit-form-${commentId}>p>textarea`)
      if (commentUpdateDiv.hidden == true) {
        commentUpdateDiv.hidden = false
      } else {
        commentUpdateDiv.hidden = true
      }
      contentTextArea.value = document.querySelector(`#comment-content-${commentId}`).textContent
    })
  })

  const commentUpdateConfirms = document.querySelectorAll('.comment-edit-form')
  commentUpdateConfirms.forEach((updateBtn) => {
    updateBtn.addEventListener('submit', (event) => {
      event.preventDefault()
      const articleId = event.target.dataset.articleId
      const commentId = event.target.dataset.commentId
      const data = {
        content: document.querySelector(`#comment-edit-form-${commentId}>p>textarea`).value,
      }
      Swal.fire({
        title: '댓글 수정하시겠습니까?',
        icon: 'question',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: '수정하기',
        cancelButtonText: '취소',
      }).then((result) => {
        if (result.isConfirmed) {
          axios({
            method:'post',
            url:`/articles/${articleId}/comments/${commentId}/update/`,
            headers: {'X-CSRFToken': csrftoken,},
            data: JSON.stringify(data),
          })
          .then((response) => {
            updateBtn.hidden = true
            document.querySelector(`#comment-content-${commentId}`).textContent = data['content']
          })
          .catch((error) => {
            console.log(error.response)
          })
        }
      })
    })
  })

  const commentUpdateCancels = document.querySelectorAll('.comment-edit-form>.cancel')
  commentUpdateCancels.forEach((cancelBtn) => {
    cancelBtn.addEventListener('click', (event) => {
      const commentId = event.target.dataset.commentId
      const commentUpdateForm = document.querySelector(`#comment-edit-form-${commentId}`)
      commentUpdateForm.hidden = true
    })
  })

  // emotion
  const emotions = document.querySelectorAll('.emotion')
  const pk = {{article.pk}}

  emotions.forEach((emotion) => {
    emotion.addEventListener('click', (event) => {
      event.preventDefault()
      const emotionId = event.target.dataset.emotionId
      const emotionCount = document.querySelector(`#emotion-${emotionId} > .emotion-count`)
      axios({
        method:'post',
        url:`/articles/${pk}/emotes/${emotionId}/${'Article'}/`,
        headers:{'X-CSRFToken': csrftoken,},       
      })
      .then((response) => {
        emotionCount.textContent = response.data.emotion_count
      })
      .catch((response) => {
        console.log(error.response)
      })
    })
  }) 

  {% for review in reviews %}
    var numStars = {{review.score}}; // 출력할 ⭐ 이모지 개수
    var review_pk = {{review.pk}}
    // stars 요소에 ⭐ 이모지 추가
    var starsEl = document.getElementById('stars-' + review_pk);

    for (let i = 0; i < numStars; i++) {
      starsEl.innerHTML += "⭐";
    }
  {% endfor %}
</script>
{% endblock content %}