accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('articles/create/', views.create, name='create'),
    path('articles/<int:article_pk>/', views.detail, name='detail'),
    path('articles/<str:category_name>/', views.category_name, name='category_name'),
    path('articles/<int:article_pk>/delete/', views.delete, name='delete'),
    path('articles/<int:article_pk>/update/', views.update, name='update'),
    path('articles/<int:article_pk>/comments/', views.comment_create, name='comment_create'),
    path('articles/<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('articles/<int:article_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('articles/<int:article_pk>/reviews/create/', views.review_create, name='review_create'),
    path('reviews/<int:review_pk>/', views.review_detail, name='review_detail'),
    path('reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('reviews/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('reviews/<int:review_pk>/comments/', views.review_comment_create, name='review_comment_create'),
    path('reviews/<int:review_pk>/comments/<int:comment_pk>/delete/', views.review_comment_delete, name='review_comment_delete'),
    path('reviews/<int:review_pk>/comments/<int:comment_pk>/update/', views.review_comment_update, name='review_comment_update'),
    path('articles/<int:pk>/emotes/<int:emotion>/<str:page>/', views.emotes, name='emotes'),
    path('search/', views.search, name='search'),
    path('search/<str:category>/', views.search_detail, name='search_detail'),
    path('plan/', views.plan, name='plan'),
    path('plan/<int:plan_pk>/delete/', views.plan_delete, name='plan_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Travel Makers</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="icon" href="{% static '/img/favicon/favicon.ico' %}">
    <link rel="stylesheet" href="{% static '/CSS/base_style.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% block head %}{% endblock head %}
  </head>
  <body class="container d-flex flex-column min-vh-100">
    {% comment %} navbar {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
      <div class="container-fluid">
        <div>
          <a class="navbar-brand" href="javascript:void(window.open('{% url 'articles:index' %}', '_self'))">🛫<img src="{% static '/img/favicon/logo.png' %}" alt="logo" style="width:12rem; height:1.1rem;"></a>
        </div>

        {% comment %} search box {% endcomment %}
        <div class="search_box">
          <form action="{% url 'articles:search' %}" method="GET" id="searchform">
            <input type="text" class="search_txt" placeholder="검색어를 입력해 주세요." name="word" id="searchbar">
            <button type="submit" class="search_btn"><i class="bi bi-search"></i></button>
          </form>
        </div>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div>
          <div class="collapse navbar-collapse" id="navbarText">
            {% if request.user.is_authenticated %}
              <div class="d-flex flex-row align-items-center">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link pe-3" href="javascript:void(window.open('{% url 'accounts:profile' user %}', '_self'))"><i class="bi bi-person-check"></i> 내 프로필</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="javascript:void(window.open('{% url 'accounts:logout' %}', '_self'))"><i class="bi bi-box-arrow-right"></i> 로그아웃</a>
                </ul>
              </div>
            {% else %}
            <div class="d-flex flex-row align-items-center">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link pe-3" data-bs-toggle="modal" data-bs-target="#exampleModal" style="cursor: pointer;">
                    <i class="bi bi-box-arrow-in-right"></i> 
                    로그인
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="javascript:void(window.open('{% url 'accounts:signup' %}', '_self'))"><i class="bi bi-person-add"></i> 회원가입</a>
                </li>
              </ul>
            </div>
            {% endif %}

          </div>
        </div>
      </div>
    </nav>

    {% comment %} menubar {% endcomment %}
    <div class="menubar">
      <nav class="navbar bg-body-tertiary">
        <div class="container-fluid d-flex justify-content-evenly">
          <a href="javascript:void(window.open('{% url 'articles:category_name' category_name='숙소' %}', '_self'))" class="menubar_text">숙소</a>
          <a href="javascript:void(window.open('{% url 'articles:category_name' category_name='자연명소' %}', '_self'))" class="menubar_text">자연명소</a>
          <a href="javascript:void(window.open('{% url 'articles:category_name' category_name='테마파크' %}', '_self'))" class="menubar_text">테마파크</a>
          <a href="javascript:void(window.open('{% url 'articles:category_name' category_name='체험관광' %}', '_self'))" class="menubar_text">체험관광</a>
          <a href="javascript:void(window.open('{% url 'articles:category_name' category_name='레저 & 액티비티' %}', '_self'))" class="menubar_text">레저 & 액티비티</a>
          <a href="javascript:void(window.open('{% url 'articles:category_name' category_name='맛집' %}', '_self'))" class="menubar_text">맛집</a>
          <a href="javascript:void(window.open('{% url 'articles:category_name' category_name='쇼핑' %}', '_self'))" class="menubar_text">쇼핑</a> 
        </div>
      </nav>
    </div>

    {% comment %} modal {% endcomment %}
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel" style="margin-left:210px;">Login</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body d-flex justify-content-center">
            <form action="{% url 'accounts:login' %}" method="post" data-bs-target="login-btn">
              {% csrf_token %}
              <input type="text" name="username" class="form-control" style="width: 250px; margin-top:20px; border-radius: 20px;" required id="id_username" placeholder="아이디">
              <input type="password" name="password" class="form-control" style="width: 250px; margin-top:15px; border-radius: 20px;" required id="id_password" placeholder="비밀번호">
              <input type="submit" id="login-btn" class="btn btn-secondary" style="width: 250px; margin-top:30px; margin-bottom:30px;" value="로그인">
            </form>
          </div>
          <div class="modal-footer d-flex justify-content-center">
            <a href="javascript:void(window.open('{% url 'accounts:signup' %}', '_self'))" class="text_signup">계정이 없으신가요?</a>
          </div>
        </div>
      </div>
    </div>

    {% comment %} main {% endcomment %}
    <div id="wrapper" class="mt-5">
      {% block content %}{% endblock content %}
    </div>

    {% comment %} top button {% endcomment %}
    <div class="topBtn">
      <div class="moveTopBtn">
        <i class="bi bi-arrow-up"></i>
      </div>
    </div>

    {% comment %} footer {% endcomment %}
    <footer class="py-2 bg-body-tertiary mt-auto">
      <div class="inner">
        <div class="footer-message d-flex justify-content-center">
          <p class="pe-3"><a href="#" style="text-decoration:none; color:#545e6f;">감수지</a></p>
          <p class="pe-3"><a href="#" style="text-decoration:none; color:#545e6f;">권준혁</a></p>
          <p class="pe-3"><a href="#" style="text-decoration:none; color:#545e6f;">박지현</a></p>
          <p class="pe-3"><a href="#" style="text-decoration:none; color:#545e6f;">소현섭</a></p>
        </div>
        <div class="footer-contact text-center">
          <address>github : https://github.com/sotthang/KDT_SemiProject1</address>
          <ul class="footer-contact-list">
            <li>
              <a href="#" style="text-decoration:none; color:#545e6f;">이용약관</a> ㅣ
              <a href="#" style="text-decoration:none; color:#545e6f;">개인정보취급방침</a> ㅣ
              <a href="#" style="text-decoration:none; color:#545e6f;">사이트맵</a> ㅣ
            </li>
          </ul>
        </div>
        <div class="footer-copyright text-center">Copyright © 2023 Travel Makers.co.,Ltd. All rights reserved.</div>
      </div>
    </footer>

    {% block script %}{% endblock script %}
    <script type="text/javascript" src="/static/JS/base_script.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>